"use client";

import { useState } from "react";
import { Sparkles, Loader2, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import ThreatExplanationCard from "@/components/ai/ThreatExplanationCard";
import { explainThreat, type SourceType, type ThreatExplanation } from "@/lib/ai";
import { apiErrorMessage } from "@/lib/errors";

/** AI Security Assistant - Feature 1. Reusable "Explain with AI" trigger, embedded wherever
 *  SecureShare already shows a malware detection, DLP violation, suspicious event, invalid
 *  signature, or quarantined file (Threat Center, DLP Center, Security Center, Files). Additive
 *  only - never replaces the existing row/card it's attached to. */
export default function ExplainWithAIButton({ sourceType, sourceId }: { sourceType: SourceType; sourceId: string }) {
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [explanation, setExplanation] = useState<ThreatExplanation | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const handleClick = async () => {
    setOpen(true);
    if (explanation || notice) return; // don't re-fetch if we already have a result for this dialog session

    const token = localStorage.getItem("token");
    if (!token) return;

    setLoading(true);
    try {
      const res = await explainThreat(sourceType, sourceId, token);
      if (res.status === "ok") {
        setExplanation(res.explanation);
      } else {
        setNotice(res.message);
      }
    } catch (err: unknown) {
      setNotice(apiErrorMessage(err, "AI explanation failed. Try again later."));
    } finally {
      setLoading(false);
    }
  };

  const handleOpenChange = (next: boolean) => {
    setOpen(next);
    if (!next) {
      // Reset so re-opening for a different file/scan fetches fresh, not stale, data.
      setExplanation(null);
      setNotice(null);
    }
  };

  return (
    <>
      <Button type="button" variant="outline" size="sm" onClick={handleClick} className="gap-1.5">
        <Sparkles size={14} className="text-primary" />
        Explain with AI
      </Button>
      <Dialog open={open} onOpenChange={handleOpenChange}>
        <DialogContent className="sm:max-w-xl max-h-[85vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles size={16} className="text-primary" />
              AI Threat Explanation
            </DialogTitle>
            <DialogDescription>Generated by the AI Security Assistant from this detection&apos;s real metadata.</DialogDescription>
          </DialogHeader>

          {loading && (
            <div className="flex items-center justify-center gap-2 py-12 text-muted-foreground text-sm">
              <Loader2 size={16} className="animate-spin" />
              Asking the AI Security Assistant...
            </div>
          )}

          {!loading && notice && (
            <div className="p-4 bg-muted border border-border rounded-lg flex items-start gap-2">
              <AlertCircle className="text-muted-foreground shrink-0 mt-0.5" size={16} />
              <p className="text-muted-foreground text-sm">{notice}</p>
            </div>
          )}

          {!loading && explanation && <ThreatExplanationCard explanation={explanation} />}
        </DialogContent>
      </Dialog>
    </>
  );
}
